language: node_js
node_js:
  - node

dist: trusty
sudo: false

# Setup xvfb
# https://github.com/electron/electron/blob/master/docs/tutorial/testing-on-headless-ci.md
# Install yarn
# https://github.com/travis-ci/travis-ci/issues/6720#issuecomment-285981417
addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
        key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
      - yarn

install:
  - yarn install
  - yarn upgrade

script:
  - yarn lint
  - yarn build:web

# after_success:
#   - bash web/bin/deploy.sh

cache:
  yarn: true
  directories:
    - node_modules

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
    - gh-pages

notifications:
  webhooks: http://webhook.hakatashi.com/travis
